// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sub.proto

package com.ebs.broker.model.protobuf;

public final class Sub {
  private Sub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.ebs.broker.model.protobuf.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STRING = 0;</code>
     */
    STRING(0),
    /**
     * <code>INT = 1;</code>
     */
    INT(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STRING = 0;</code>
     */
    public static final int STRING_VALUE = 0;
    /**
     * <code>INT = 1;</code>
     */
    public static final int INT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    public static Type forNumber(int value) {
      switch (value) {
        case 0: return STRING;
        case 1: return INT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ebs.broker.model.protobuf.Sub.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.ebs.broker.model.protobuf.Type)
  }

  public interface SubscriptionPropertyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ebs.broker.model.protobuf.SubscriptionProperty)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string fieldName = 1;</code>
     */
    java.lang.String getFieldName();
    /**
     * <code>string fieldName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldNameBytes();

    /**
     * <code>string operator = 2;</code>
     */
    java.lang.String getOperator();
    /**
     * <code>string operator = 2;</code>
     */
    com.google.protobuf.ByteString
        getOperatorBytes();

    /**
     * <code>string fieldValue = 3;</code>
     */
    java.lang.String getFieldValue();
    /**
     * <code>string fieldValue = 3;</code>
     */
    com.google.protobuf.ByteString
        getFieldValueBytes();

    /**
     * <pre>
     *defaults to STRING
     * </pre>
     *
     * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
     */
    int getFieldTypeValue();
    /**
     * <pre>
     *defaults to STRING
     * </pre>
     *
     * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
     */
    com.ebs.broker.model.protobuf.Sub.Type getFieldType();
  }
  /**
   * Protobuf type {@code com.ebs.broker.model.protobuf.SubscriptionProperty}
   */
  public  static final class SubscriptionProperty extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ebs.broker.model.protobuf.SubscriptionProperty)
      SubscriptionPropertyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscriptionProperty.newBuilder() to construct.
    private SubscriptionProperty(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscriptionProperty() {
      fieldName_ = "";
      operator_ = "";
      fieldValue_ = "";
      fieldType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubscriptionProperty(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              operator_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fieldValue_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              fieldType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.class, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder.class);
    }

    public static final int FIELDNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fieldName_;
    /**
     * <code>string fieldName = 1;</code>
     */
    public java.lang.String getFieldName() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldName_ = s;
        return s;
      }
    }
    /**
     * <code>string fieldName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldNameBytes() {
      java.lang.Object ref = fieldName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object operator_;
    /**
     * <code>string operator = 2;</code>
     */
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      }
    }
    /**
     * <code>string operator = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDVALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object fieldValue_;
    /**
     * <code>string fieldValue = 3;</code>
     */
    public java.lang.String getFieldValue() {
      java.lang.Object ref = fieldValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fieldValue_ = s;
        return s;
      }
    }
    /**
     * <code>string fieldValue = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFieldValueBytes() {
      java.lang.Object ref = fieldValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fieldValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELDTYPE_FIELD_NUMBER = 4;
    private int fieldType_;
    /**
     * <pre>
     *defaults to STRING
     * </pre>
     *
     * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
     */
    public int getFieldTypeValue() {
      return fieldType_;
    }
    /**
     * <pre>
     *defaults to STRING
     * </pre>
     *
     * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
     */
    public com.ebs.broker.model.protobuf.Sub.Type getFieldType() {
      @SuppressWarnings("deprecation")
      com.ebs.broker.model.protobuf.Sub.Type result = com.ebs.broker.model.protobuf.Sub.Type.valueOf(fieldType_);
      return result == null ? com.ebs.broker.model.protobuf.Sub.Type.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFieldNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fieldName_);
      }
      if (!getOperatorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operator_);
      }
      if (!getFieldValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fieldValue_);
      }
      if (fieldType_ != com.ebs.broker.model.protobuf.Sub.Type.STRING.getNumber()) {
        output.writeEnum(4, fieldType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFieldNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fieldName_);
      }
      if (!getOperatorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, operator_);
      }
      if (!getFieldValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fieldValue_);
      }
      if (fieldType_ != com.ebs.broker.model.protobuf.Sub.Type.STRING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, fieldType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ebs.broker.model.protobuf.Sub.SubscriptionProperty)) {
        return super.equals(obj);
      }
      com.ebs.broker.model.protobuf.Sub.SubscriptionProperty other = (com.ebs.broker.model.protobuf.Sub.SubscriptionProperty) obj;

      if (!getFieldName()
          .equals(other.getFieldName())) return false;
      if (!getOperator()
          .equals(other.getOperator())) return false;
      if (!getFieldValue()
          .equals(other.getFieldValue())) return false;
      if (fieldType_ != other.fieldType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELDNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFieldName().hashCode();
      hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getOperator().hashCode();
      hash = (37 * hash) + FIELDVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFieldValue().hashCode();
      hash = (37 * hash) + FIELDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + fieldType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ebs.broker.model.protobuf.Sub.SubscriptionProperty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ebs.broker.model.protobuf.SubscriptionProperty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ebs.broker.model.protobuf.SubscriptionProperty)
        com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.class, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder.class);
      }

      // Construct using com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fieldName_ = "";

        operator_ = "";

        fieldValue_ = "";

        fieldType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor;
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getDefaultInstanceForType() {
        return com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.getDefaultInstance();
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty build() {
        com.ebs.broker.model.protobuf.Sub.SubscriptionProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty buildPartial() {
        com.ebs.broker.model.protobuf.Sub.SubscriptionProperty result = new com.ebs.broker.model.protobuf.Sub.SubscriptionProperty(this);
        result.fieldName_ = fieldName_;
        result.operator_ = operator_;
        result.fieldValue_ = fieldValue_;
        result.fieldType_ = fieldType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebs.broker.model.protobuf.Sub.SubscriptionProperty) {
          return mergeFrom((com.ebs.broker.model.protobuf.Sub.SubscriptionProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebs.broker.model.protobuf.Sub.SubscriptionProperty other) {
        if (other == com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.getDefaultInstance()) return this;
        if (!other.getFieldName().isEmpty()) {
          fieldName_ = other.fieldName_;
          onChanged();
        }
        if (!other.getOperator().isEmpty()) {
          operator_ = other.operator_;
          onChanged();
        }
        if (!other.getFieldValue().isEmpty()) {
          fieldValue_ = other.fieldValue_;
          onChanged();
        }
        if (other.fieldType_ != 0) {
          setFieldTypeValue(other.getFieldTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ebs.broker.model.protobuf.Sub.SubscriptionProperty parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ebs.broker.model.protobuf.Sub.SubscriptionProperty) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object fieldName_ = "";
      /**
       * <code>string fieldName = 1;</code>
       */
      public java.lang.String getFieldName() {
        java.lang.Object ref = fieldName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fieldName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldNameBytes() {
        java.lang.Object ref = fieldName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fieldName = 1;</code>
       */
      public Builder setFieldName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fieldName = 1;</code>
       */
      public Builder clearFieldName() {
        
        fieldName_ = getDefaultInstance().getFieldName();
        onChanged();
        return this;
      }
      /**
       * <code>string fieldName = 1;</code>
       */
      public Builder setFieldNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object operator_ = "";
      /**
       * <code>string operator = 2;</code>
       */
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operator = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operator = 2;</code>
       */
      public Builder setOperator(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        operator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 2;</code>
       */
      public Builder clearOperator() {
        
        operator_ = getDefaultInstance().getOperator();
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 2;</code>
       */
      public Builder setOperatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        operator_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fieldValue_ = "";
      /**
       * <code>string fieldValue = 3;</code>
       */
      public java.lang.String getFieldValue() {
        java.lang.Object ref = fieldValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fieldValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fieldValue = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFieldValueBytes() {
        java.lang.Object ref = fieldValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fieldValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fieldValue = 3;</code>
       */
      public Builder setFieldValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fieldValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fieldValue = 3;</code>
       */
      public Builder clearFieldValue() {
        
        fieldValue_ = getDefaultInstance().getFieldValue();
        onChanged();
        return this;
      }
      /**
       * <code>string fieldValue = 3;</code>
       */
      public Builder setFieldValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fieldValue_ = value;
        onChanged();
        return this;
      }

      private int fieldType_ = 0;
      /**
       * <pre>
       *defaults to STRING
       * </pre>
       *
       * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
       */
      public int getFieldTypeValue() {
        return fieldType_;
      }
      /**
       * <pre>
       *defaults to STRING
       * </pre>
       *
       * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
       */
      public Builder setFieldTypeValue(int value) {
        fieldType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *defaults to STRING
       * </pre>
       *
       * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.Type getFieldType() {
        @SuppressWarnings("deprecation")
        com.ebs.broker.model.protobuf.Sub.Type result = com.ebs.broker.model.protobuf.Sub.Type.valueOf(fieldType_);
        return result == null ? com.ebs.broker.model.protobuf.Sub.Type.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *defaults to STRING
       * </pre>
       *
       * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
       */
      public Builder setFieldType(com.ebs.broker.model.protobuf.Sub.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fieldType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *defaults to STRING
       * </pre>
       *
       * <code>.com.ebs.broker.model.protobuf.Type fieldType = 4;</code>
       */
      public Builder clearFieldType() {
        
        fieldType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ebs.broker.model.protobuf.SubscriptionProperty)
    }

    // @@protoc_insertion_point(class_scope:com.ebs.broker.model.protobuf.SubscriptionProperty)
    private static final com.ebs.broker.model.protobuf.Sub.SubscriptionProperty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ebs.broker.model.protobuf.Sub.SubscriptionProperty();
    }

    public static com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscriptionProperty>
        PARSER = new com.google.protobuf.AbstractParser<SubscriptionProperty>() {
      @java.lang.Override
      public SubscriptionProperty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscriptionProperty(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubscriptionProperty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscriptionProperty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ebs.broker.model.protobuf.Subscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> 
        getPropertyList();
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getProperty(int index);
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    int getPropertyCount();
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    java.util.List<? extends com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder> 
        getPropertyOrBuilderList();
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder getPropertyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.ebs.broker.model.protobuf.Subscription}
   */
  public  static final class Subscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ebs.broker.model.protobuf.Subscription)
      SubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscription() {
      property_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Subscription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                property_ = new java.util.ArrayList<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty>();
                mutable_bitField0_ |= 0x00000001;
              }
              property_.add(
                  input.readMessage(com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          property_ = java.util.Collections.unmodifiableList(property_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebs.broker.model.protobuf.Sub.Subscription.class, com.ebs.broker.model.protobuf.Sub.Subscription.Builder.class);
    }

    public static final int PROPERTY_FIELD_NUMBER = 1;
    private java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> property_;
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    public java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> getPropertyList() {
      return property_;
    }
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    public java.util.List<? extends com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder> 
        getPropertyOrBuilderList() {
      return property_;
    }
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    public int getPropertyCount() {
      return property_.size();
    }
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getProperty(int index) {
      return property_.get(index);
    }
    /**
     * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
     */
    public com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder getPropertyOrBuilder(
        int index) {
      return property_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < property_.size(); i++) {
        output.writeMessage(1, property_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < property_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, property_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ebs.broker.model.protobuf.Sub.Subscription)) {
        return super.equals(obj);
      }
      com.ebs.broker.model.protobuf.Sub.Subscription other = (com.ebs.broker.model.protobuf.Sub.Subscription) obj;

      if (!getPropertyList()
          .equals(other.getPropertyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPropertyCount() > 0) {
        hash = (37 * hash) + PROPERTY_FIELD_NUMBER;
        hash = (53 * hash) + getPropertyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ebs.broker.model.protobuf.Sub.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ebs.broker.model.protobuf.Sub.Subscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ebs.broker.model.protobuf.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ebs.broker.model.protobuf.Subscription)
        com.ebs.broker.model.protobuf.Sub.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ebs.broker.model.protobuf.Sub.Subscription.class, com.ebs.broker.model.protobuf.Sub.Subscription.Builder.class);
      }

      // Construct using com.ebs.broker.model.protobuf.Sub.Subscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPropertyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ebs.broker.model.protobuf.Sub.internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor;
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.Subscription getDefaultInstanceForType() {
        return com.ebs.broker.model.protobuf.Sub.Subscription.getDefaultInstance();
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.Subscription build() {
        com.ebs.broker.model.protobuf.Sub.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ebs.broker.model.protobuf.Sub.Subscription buildPartial() {
        com.ebs.broker.model.protobuf.Sub.Subscription result = new com.ebs.broker.model.protobuf.Sub.Subscription(this);
        int from_bitField0_ = bitField0_;
        if (propertyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            property_ = java.util.Collections.unmodifiableList(property_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.property_ = property_;
        } else {
          result.property_ = propertyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ebs.broker.model.protobuf.Sub.Subscription) {
          return mergeFrom((com.ebs.broker.model.protobuf.Sub.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ebs.broker.model.protobuf.Sub.Subscription other) {
        if (other == com.ebs.broker.model.protobuf.Sub.Subscription.getDefaultInstance()) return this;
        if (propertyBuilder_ == null) {
          if (!other.property_.isEmpty()) {
            if (property_.isEmpty()) {
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePropertyIsMutable();
              property_.addAll(other.property_);
            }
            onChanged();
          }
        } else {
          if (!other.property_.isEmpty()) {
            if (propertyBuilder_.isEmpty()) {
              propertyBuilder_.dispose();
              propertyBuilder_ = null;
              property_ = other.property_;
              bitField0_ = (bitField0_ & ~0x00000001);
              propertyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPropertyFieldBuilder() : null;
            } else {
              propertyBuilder_.addAllMessages(other.property_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ebs.broker.model.protobuf.Sub.Subscription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ebs.broker.model.protobuf.Sub.Subscription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> property_ =
        java.util.Collections.emptyList();
      private void ensurePropertyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          property_ = new java.util.ArrayList<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty>(property_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ebs.broker.model.protobuf.Sub.SubscriptionProperty, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder, com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder> propertyBuilder_;

      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> getPropertyList() {
        if (propertyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(property_);
        } else {
          return propertyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public int getPropertyCount() {
        if (propertyBuilder_ == null) {
          return property_.size();
        } else {
          return propertyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty getProperty(int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);
        } else {
          return propertyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder setProperty(
          int index, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.set(index, value);
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder setProperty(
          int index, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.set(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder addProperty(com.ebs.broker.model.protobuf.Sub.SubscriptionProperty value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder addProperty(
          int index, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty value) {
        if (propertyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropertyIsMutable();
          property_.add(index, value);
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder addProperty(
          com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder addProperty(
          int index, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder builderForValue) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.add(index, builderForValue.build());
          onChanged();
        } else {
          propertyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder addAllProperty(
          java.lang.Iterable<? extends com.ebs.broker.model.protobuf.Sub.SubscriptionProperty> values) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, property_);
          onChanged();
        } else {
          propertyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder clearProperty() {
        if (propertyBuilder_ == null) {
          property_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          propertyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public Builder removeProperty(int index) {
        if (propertyBuilder_ == null) {
          ensurePropertyIsMutable();
          property_.remove(index);
          onChanged();
        } else {
          propertyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder getPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder getPropertyOrBuilder(
          int index) {
        if (propertyBuilder_ == null) {
          return property_.get(index);  } else {
          return propertyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public java.util.List<? extends com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder> 
           getPropertyOrBuilderList() {
        if (propertyBuilder_ != null) {
          return propertyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(property_);
        }
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder addPropertyBuilder() {
        return getPropertyFieldBuilder().addBuilder(
            com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder addPropertyBuilder(
          int index) {
        return getPropertyFieldBuilder().addBuilder(
            index, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ebs.broker.model.protobuf.SubscriptionProperty property = 1;</code>
       */
      public java.util.List<com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder> 
           getPropertyBuilderList() {
        return getPropertyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ebs.broker.model.protobuf.Sub.SubscriptionProperty, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder, com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder> 
          getPropertyFieldBuilder() {
        if (propertyBuilder_ == null) {
          propertyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ebs.broker.model.protobuf.Sub.SubscriptionProperty, com.ebs.broker.model.protobuf.Sub.SubscriptionProperty.Builder, com.ebs.broker.model.protobuf.Sub.SubscriptionPropertyOrBuilder>(
                  property_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          property_ = null;
        }
        return propertyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ebs.broker.model.protobuf.Subscription)
    }

    // @@protoc_insertion_point(class_scope:com.ebs.broker.model.protobuf.Subscription)
    private static final com.ebs.broker.model.protobuf.Sub.Subscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ebs.broker.model.protobuf.Sub.Subscription();
    }

    public static com.ebs.broker.model.protobuf.Sub.Subscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscription>
        PARSER = new com.google.protobuf.AbstractParser<Subscription>() {
      @java.lang.Override
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Subscription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ebs.broker.model.protobuf.Sub.Subscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ebs_broker_model_protobuf_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsub.proto\022\035com.ebs.broker.model.protob" +
      "uf\"\207\001\n\024SubscriptionProperty\022\021\n\tfieldName" +
      "\030\001 \001(\t\022\020\n\010operator\030\002 \001(\t\022\022\n\nfieldValue\030\003" +
      " \001(\t\0226\n\tfieldType\030\004 \001(\0162#.com.ebs.broker" +
      ".model.protobuf.Type\"U\n\014Subscription\022E\n\010" +
      "property\030\001 \003(\01323.com.ebs.broker.model.pr" +
      "otobuf.SubscriptionProperty*\033\n\004Type\022\n\n\006S" +
      "TRING\020\000\022\007\n\003INT\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ebs_broker_model_protobuf_SubscriptionProperty_descriptor,
        new java.lang.String[] { "FieldName", "Operator", "FieldValue", "FieldType", });
    internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ebs_broker_model_protobuf_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ebs_broker_model_protobuf_Subscription_descriptor,
        new java.lang.String[] { "Property", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
